#!/bin/bash

REPODIR=..
EMACSDIR=/home/$USER/.emacs.d/

FILES=( ${REPODIR}/config/config.org
	${REPODIR}/config/org-agenda-config.org
	${REPODIR}/abbrev_defs ) 

bold=$(tput bold)
normal=$(tput sgr0)

for item in ${FILES[@]}; do

    # para a leitura
    REMOTEFILE=$item
    BASEFILE=$(basename $item)

    if [[ "$item" == *"config"* ]]; then
	LOCALFILE_L=${EMACSDIR}config/$(basename $item)

	diff -s --color=always $LOCALFILE_L $REMOTEFILE

	while true; do
	    echo "Atualizar o $BASEFILE ${bold}local${normal} ou o ${bold}remoto${normal} (deste repositório)?" 
	    read -p "[L=local/R=remoto/P=pular/C=cancelar]: " ANSWER 
	    ANSWER_S=${ANSWER:0:1}

	    if [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) ==  "r" ]]; then 
		echo "atualizando $BASEFILE deste repositório..."; 
		cp --verbose $LOCALFILE_L $REMOTEFILE # update remote
		break

	    elif [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) == "l" ]]; then
		echo "atualizando $BASEFILE local..."; 
		cp --verbose $REMOTEFILE $LOCALFILE_L # update local 
		break

	    elif [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) == "p" ]]; then
		echo "pulando este..."
		break

	    elif [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) == "c" ]]; then
		echo "cancelando..." ; sleep 1
		exit 1

	    else
		printf "\n"; echo "${bold}Não é uma resposta válida.${normal}" 
		continue
	    fi
	done
    else
	LOCALFILE_L=${EMACSDIR}$(basename $item)
	diff -s --color=always $LOCALFILE_L $REMOTEFILE

	while true ; do
	    echo "Atualizar o $BASEFILE ${bold}local${normal} ou o ${bold}remoto${normal} (deste repositório)?" 
	    read -p "[L=local/R=remoto/P=pular/Outro=cancelar]: " ANSWER 
	    ANSWER_S=${ANSWER:0:1}

	    if [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) ==  "r" ]]; then 
		echo "atualizando $BASEFILE deste repositório..."; 
		cp --verbose $LOCALFILE_L $REMOTEFILE # update remote
		break

	    elif [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) == "l" ]]; then
		echo "atualizando $BASEFILE local...";
		cp --verbose $REMOTEFILE $LOCALFILE_L # update local 
		break

	    elif [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) == "p" ]]; then
		echo "pulando este..."
		break

	    elif [[ $( echo $ANSWER_S | awk '{print tolower($0)}' ) == "c" ]]; then
		echo "cancelando..." ; sleep 1
		exit 1

	    else
		printf "\n"; echo "${bold}Não é uma resposta válida.${normal}" 
		continue
	    fi
	done
    fi
done

echo "Done. Quitting..." ; sleep 1
