#!/bin/sh

ORGDIR=/media/$USER/HDD_1/syncthing/org/

for file in ./org_bases/*.org
	do
		curr=$(basename $file)
		if [ ! -e ${ORGDIR}${curr} ] 
		then
			echo "creating $file in $ORGDIR"
			cp $file ${ORGDIR}${curr}		
		else
			echo "file $(basename $file) already exists already exists in target directory"
		fi
	done
