#+TITLE: Referências
#+AUTHOR: Paulo
#+OPTIONS: p:nil todo:t \n:t date:nil c:nil prop:t stat:t tags:t d:t

Página de referências

* Capture 
  
* Estatística 
** Notes 
*** Covariance
    You use it to measure the joint variability of two random variables. It measures only direction  (whether they are positively or negatively co-varying).
    Should be applied only to linearly varying variables.
*** Correlation
    It measures the strength and direction of the correlation of variables, viz., whether they are positively or negatively correlated, and whether that correlation is weak or strong.
    Should be applied only to linearly varying variables.
*** Linear regression
    Tries to verify the power of a dependent variable to predict the result that is obtained through the influence of the independent variable. 
    Regression estimates are used to explain the relationship between one dependent variable and one or more independent variables.  
    Should be applied only to linearly varying variables.
*** ANOVA (Analysis of Variance)
    Verifies if differente sample menas within an overall mean come from the same population or from differnet populations (h0)
    F = Between/Within | Between = distance from the means of subsamples to the overall mean, within = spread of samples in relation to overall spread
** Resources
* Stock Image Sources
* Emacs notes:
** Internal linking
*** I can create links in the following way:

    This link goes to the [[Capture][Capture headline]].

*** And then I can create another headline
    :PROPERTIES:
    :CUSTOM_ID: showoff123
    :END:

    heyyy

*** And then I can call it

    Like [[named_item][this]] 
    This, however, only works on headlines with content inside them. Dunno why.

**** And give it a name like below:

    #+NAME: named_item 
    Hey, apple

*** I can also create links like this:

    I can give something a custom ID. In the "and then I can create another headline" headline I wrote for it a custom ID. I can go to it through [[#showoff123][this]] link.

*** There is also something called  "Radio targets".

    If I write down the name Lewin, for example, it will create links everywhere the name "Lewin" is written, an they will point to where the <<<radio>>> target is..

** External linking
*** Besides linking to websites, files and whatnot, I can also create links for other notes within my org environment.

    Like [[id:896a9a8b-6697-4485-baca-ab2434a32839][this]] 

** Agenda
*** Follow mode:

    You can activate follow mode in the evil-agenda with shif+f or F

** Clocking
   :LOGBOOK:
   - Note taken on [2020-04-05 dom 22:32] \\
     Isso é útil para averiguar quanto tempo duram as tarefas
   :END:

*** You can start a stopwatch with C-c C-x C-i
*** You can end it with C-c C-x C-o
*** You can restart it with C-c C-x C-x
    :LOGBOOK:
    - Note taken on [2020-04-05 dom 22:34] \\
      This is useful for when you are interrupted
    :END:

*** You can restart it with a menu with C-u C-c C-x C-x
*** You can cancel it with C-c C-x C-q
*** You can highlight time durations with C-c C-x C-d
    :LOGBOOK:
    - Note taken on [2020-04-05 dom 22:37] \\
      This shows the time being added together as well if the headlines are positioned within hierarchies
    :END:

*** And you can jump to the currently-being-clocked task with C-c C-x C-j
** Example for a simple table

|-------+---------------+--------------------+--------|
| Role  | Name          | Adress             | City   |
|-------+---------------+--------------------+--------|
| POTUS | Barack Obama  | 600 Northward Ave. | Jersey |
| POTR  | Vladmir Putin | Kremlin            | Moscow |
|-------+---------------+--------------------+--------|
|       |               |                    |        |




